name: Nightly Tests

on:
  schedule:
    # Run at 2 AM UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  extensive-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build C++ extension
        run: |
          pip install pybind11
          python setup.py build_ext --inplace

      - name: Run all tests (including slow)
        run: |
          pytest tests/ tests_api/ -v --cov=. --cov-report=term

      - name: Run performance benchmarks
        run: |
          pytest tests/test_performance.py -v -m benchmark

      - name: Check for performance regressions
        run: |
          pytest tests/test_performance.py::TestPerformanceRegression -v